[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_hub = "68LstwZhYt14pDyVtzLKQ9yfXntNDauhAaH5TMQD1fRj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/solana-hub-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
