[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_hub = "EsE5KPaDVc5wrrmJSDCUbaWSds35x56A3XkDUKkexHb6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/solana-hub-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
